name: Deploy Frontend

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  PROJECT_NAME: resume-analyzer
  ENVIRONMENT: dev
  AWS_REGION: ap-south-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubOIDC-TerraformRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push frontend Docker image
        run: |
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.PROJECT_NAME }}-${{ env.ENVIRONMENT }}-frontend:latest
          echo "Building image: $IMAGE_URI"
          docker build -f docker/frontend.Dockerfile -t $IMAGE_URI .
          docker push $IMAGE_URI

      - name: Force ECS Service redeploy
        run: |
          aws ecs update-service \
            --cluster ${{ env.PROJECT_NAME }}-${{ env.ENVIRONMENT }}-frontend-cluster \
            --service ${{ env.PROJECT_NAME }}-${{ env.ENVIRONMENT }}-frontend-svc \
            --force-new-deployment \
            --region ${{ env.AWS_REGION }}